### ISSUE TITLE
[Bug] XML Parsing Error: no root element found

### ISSUE THREAD

**Issue by mjthoraval** [windingwind/zotero-actions-tags#197] opened 2023-11-23 14:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using the latest Zotero and the latest plugin?

- [X] I have confirmed I'm using the latest Zotero and the latest plugin

### Environment

- OS: Windows 10
- Zotero Version: 7.0.0-beta.51+7c5600913 (64-bit)
- Plugin Version: 1.0.0-25

### Describe the bug

I get the following error when using the Copy Item link: https://github.com/windingwind/zotero-actions-tags/discussions/115
![image](https://github.com/windingwind/zotero-actions-tags/assets/36054098/a357239f-b681-416b-9657-42033b3fd240)

I also get the same error when using the Related selected items: https://github.com/windingwind/zotero-actions-tags/discussions/164
So I guess it is a general problem.

### Debug Output

1700749603235	addons.xpi	WARN	Checking C:\Program Files\Zotero\distribution\extensions for addons

[JavaScript Error: "NS_NOINTERFACE: " {file: "resource://gre/modules/ComponentUtils.jsm" line: 90}]
createInstance@resource://gre/modules/ComponentUtils.jsm:90:36

1700749604753	addons.xpi	WARN	Addon with ID undefined already installed, older version will be disabled

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "Error: Addon must include an id, version, and type" {file: "resource://gre/modules/addons/XPIProvider.jsm" line: 1710}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsITelemetry.getHistogramById]" {file: "resource://gre/modules/TerminatorTelemetry.jsm" line: 87}]

[JavaScript Error: "NS_ERROR_NOT_AVAILABLE" {file: "resource://gre/modules/PartitioningExceptionListService.jsm" line: 92}]

[JavaScript Error: "NotFoundError: Could not get children of file(C:\Users\mjthoraval\AppData\Roaming\Zotero\Zotero\Crash Reports\events) because it does not exist" {file: "resource://gre/modules/CrashManager.jsm" line: 682}]
_getUnprocessedEventsFiles/<@resource://gre/modules/CrashManager.jsm:682:12

[JavaScript Error: "TypeError: headline is null" {file: "chrome://zotero/content/xpcom/progressWindow.js" line: 157}]
changeHeadline@chrome://zotero/content/xpcom/progressWindow.js:157:12
_onWindowLoaded@chrome://zotero/content/xpcom/progressWindow.js:470:35

appName => Zotero, version => 7.0.0-beta.51+7c5600913, os => Windows 10.0 19045, locale => en-GB, extensions => Actions and Tags for Zotero (1.0.0-25, extension), Open PDF for Zotero (0.0.8, extension, disabled), Zotero PDF Preview (1.0.0-4, extension, disabled), Zotero Better Authors (4.0.2, extension, disabled), Translate for Zotero (1.1.0-21, extension, disabled), Better Notes for Zotero (1.1.4-36, extension, disabled), Better BibTex for Zotero (6.7.137, extension, disabled)

(3)(+0155299): itemTree.render(). Displaying Item Tree

(3)(+0000013): Viewing item in pane 0

(4)(+0000003): Registering notifier observer 'itemBox_yN' for [item]

(3)(+0000005): Refreshing item box

(3)(+0000081): Zotero.Items.keepParents() is deprecated -- use Zotero.Items.keepTopLevel() instead

(4)(+0000001): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [37558, 'https://www.mdpi.com/2079-6412/10/6/592']

(4)(+0000044): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [37558, 'https://www.mdpi.com/2079-6412/10/6/592']

(4)(+0000003): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [37558, 'https://www.mdpi.com/2079-6412/10/6/592']

(4)(+0000013): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [37558, 'https://www.mdpi.com/2079-6412/10/6/592']

(4)(+0000003): SELECT IA.itemID FROM itemAttachments IA NATURAL JOIN items I LEFT JOIN itemData ID ON (IA.itemID=ID.itemID AND fieldID=13) LEFT JOIN itemDataValues IDV ON (ID.valueID=IDV.valueID) WHERE parentItemID=? AND linkMode NOT IN (3) AND IA.itemID NOT IN (SELECT itemID FROM deletedItems) ORDER BY contentType='application/pdf' DESC, value=? DESC, dateAdded ASC [37558, 'https://www.mdpi.com/2079-6412/10/6/592']

(4)(+0003522): Beginning DB transaction 14uKpKRO

(4)(+0000003): Committed DB transaction 14uKpKRO

(3)(+0000001): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Copy item link\r\n// @author windingwind\r\n// @link https://github.com/windingwind/zotero-actions-tags/discussions/115\r\n// @usage Select an item in the library and press the assigned shortcut keys\r\n\r\nif (!item) {\r\n\treturn \"[Copy Item Link] item is empty\";\r\n}\r\n\r\nconst libraryType = item.library.libraryType;\r\nconst key = item.key;\r\n\r\nlet uri;\r\n\r\nif (libraryType === \"user\") {\r\n\turi = \"zotero://select/library/items/\" + key;\r\n}\r\nelse {\r\n\tconst groupID = Zotero.Libraries.get(item.libraryID).groupID;\r\n\turi = \"zotero://select/groups/\" + groupID + \"/items/\" + key;\r\n}\r\n\r\nconst clipboard = new Zotero.ActionsTags.api.utils.ClipboardHelper();\r\n\r\nlet linkText;\r\n// Use title\r\nlinkText = item.getField(\"title\");\r\n// Use citation key\r\n// linkText = item.getField(\"citationKey\");\r\n\r\nlet plainText;\r\n// Use plain-text\r\nplainText = uri;\r\n// Use MarkDown\r\n// plainURI = `[${linkText}](${uri})`\r\nclipboard\r\n\t.addText(plainText, \"text/unicode\")\r\n\t.addText(`<a href=\"${uri}\">${linkText}</a>`, \"text/html\")\r\n\t.copy();\r\n\r\nreturn `[Copy Item Link] item link ${uri} copied.`","shortcut":"","enabled":true,"menu":"📋 Copy item-link","name":"93 - Copy item-link"} {"itemIDs":[37558]}

(4)(+0000014): Beginning DB transaction vyBhrjXT

(4)(+0000004): Item 37558 has not changed

(4)(+0000001): Committed DB transaction vyBhrjXT

(3)(+0000001): [Actions and Tags for Zotero] applyAction {"event":0,"operation":4,"data":"// Copy item link\r\n// @author windingwind\r\n// @link https://github.com/windingwind/zotero-actions-tags/discussions/115\r\n// @usage Select an item in the library and press the assigned shortcut keys\r\n\r\nif (!item) {\r\n\treturn \"[Copy Item Link] item is empty\";\r\n}\r\n\r\nconst libraryType = item.library.libraryType;\r\nconst key = item.key;\r\n\r\nlet uri;\r\n\r\nif (libraryType === \"user\") {\r\n\turi = \"zotero://select/library/items/\" + key;\r\n}\r\nelse {\r\n\tconst groupID = Zotero.Libraries.get(item.libraryID).groupID;\r\n\turi = \"zotero://select/groups/\" + groupID + \"/items/\" + key;\r\n}\r\n\r\nconst clipboard = new Zotero.ActionsTags.api.utils.ClipboardHelper();\r\n\r\nlet linkText;\r\n// Use title\r\nlinkText = item.getField(\"title\");\r\n// Use citation key\r\n// linkText = item.getField(\"citationKey\");\r\n\r\nlet plainText;\r\n// Use plain-text\r\nplainText = uri;\r\n// Use MarkDown\r\n// plainURI = `[${linkText}](${uri})`\r\nclipboard\r\n\t.addText(plainText, \"text/unicode\")\r\n\t.addText(`<a href=\"${uri}\">${linkText}</a>`, \"text/html\")\r\n\t.copy();\r\n\r\nreturn `[Copy Item Link] item link ${uri} copied.`","shortcut":"","enabled":true,"menu":"📋 Copy item-link","name":"93 - Copy item-link"} {"itemID":37558}

(3)(+0018526): itemTree.render(). Displaying Item Tree

### Anything else?

I see that there is a related post in the forums:
https://forums.zotero.org/discussion/109402/zotero-7-beta-report-a-error-xml-parsing-error-no-root-element-found
So it may be a more general bug. But I can only reproduce reliably with this plugin so far.

**Comment by windingwind** [comment] 2023-11-23 14:40
Well, this seems to be an error with loading the progressWindow, a built-in module of Zotero. I haven't update the plugin for weeks, so it's unlikely to be caused by this plugin. Do you have any idea when this starts?

**Comment by windingwind** [comment] 2023-11-23 15:37
Try to run this in Tool - Developer - `runJS` and see what happens:

```js
progressWin = new Zotero.ProgressWindow({
  closeOnClick: false
});
progressWin.changeHeadline('test');
progress = new progressWin.ItemProgress(
  undefined, 'test'
);
progressWin.show();
```

If that can reproduce the bug, disable all plugins and enable them one by one with restart and run to see when it starts to happen.

**Comment by mjthoraval** [comment] 2023-11-23 15:43
Your script can trigger the bug with all plugins disabled.

Should I report in the forums, or does it fit better in the devs forums?
https://groups.google.com/g/zotero-dev

I have seen this post also in the forums where they had observed a similar error message and found a fix to it:
https://forums.zotero.org/discussion/105584/an-error-occurred-importing-the-selected-file-with-xml-contextobject
It is probably different, but it may have some useful information in it.

**Comment by windingwind** [comment] 2023-11-23 15:54
Yes, definitely. If you can reproduce when all plugins are disabled (and be sure to restart Zotero before test), then please go direct to the forums.

I don't think this should go to dev list, since you are not a developer (and this is not something that related to plugin).

**Comment by windingwind** [comment] 2023-11-23 15:56
And it's not related to the "found a fix" thread I believe. A debug ID and steps to reproduce would be enough.

**Comment by mjthoraval** [comment] 2023-11-23 16:15
Done: https://forums.zotero.org/discussion/109677/zotero-7-beta-xml-parsing-error-no-root-element-found
Thank you.

**Comment by windingwind** [comment] 2023-11-28 02:30
Seems like the problem is resolved in the thread above. Closed.

**Closed by windingwind** 2023-11-28 02:30 UTC
Labels: bug
